use_frameworks!

platform :ios, '8.0'

target 'AaronOC_Example' do
  pod 'AaronOC', :path => '../'

  target 'AaronOC_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
